### ISSUE TITLE
Team management might be easier through the GH team interface

### ISSUE THREAD

**Issue by simonwex** [codetree/feedback#13]
Linking a Codetree organization to a Github team might provide a low-effort mechanism for team management.

https://developer.github.com/v3/orgs/teams/

**Comment by 0b10011** [comment]
:+1:

**Comment by 0b10011** [comment]
And, just in time: [Organization Webhooks](https://github.com/blog/1933-introducing-organization-webhooks)

**Comment by chadbay** [comment]
:+1: How do I add another admin to an organization? I see a way to do it on the project level, but not at the organizational level.

**Comment by derrickreimer** [comment]
@chadbay just got back via email, but I'll copy here to get this info in the public sphere:

Currently the owner is the only one who can create projects, because we rely on the organization owner's credentials to periodically poll the GitHub API for certain changes. This keeps it simple on our end, but I do recognize it's a bit limiting for users.

We'll work on improving permissions soon.

**Comment by derrickreimer** [comment]
Closing for now
