### ISSUE TITLE
User's point total no longer updates

### ISSUE THREAD

**Issue by ezra-g** [codetree/feedback#139]
It's great having the user's point total displayed at the top of the column. I've noticed that the column total takes 5 or more seconds to update after changing a single value. The teams I'm working with typically update point estimates during sprint planing, which is typically a time-sensitive with several people present, so having these kinds of interactions happen quickly would be particularly valuable. 
![](http://g.recordit.co/IdH00CJBdu.gif)

**Comment by ezra-g** [comment]
I've noticed in some cases that the point total never ends up updating and we have a 503 in the browser console for https://codetree.com/projects/z9qh/issues/sizes.json?labels=all%3A(status%3A+next+sprint%2Cteam%3A+1)

**Comment by ezra-g** [comment]
Actually, we appear to be getting a 503 every time we update points for an individual issue.

**Comment by derrickreimer** [comment]
Background updating of point totals is temporarily disabled. We are
encountering floods of heavy queries from this, presumably due to many
simultaneous requests from open browsers that want updated totals for their
given view every time points are updated. This is adversely impacting site
performance. I'm working on some performance enhancements and throttling
measures.

On Friday, November 6, 2015, Ezra Gildesgame notifications@github.com
wrote:

> Actually, we appear to be getting a 503 every time we update points for an
> individual issue.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/codetree/feedback/issues/139#issuecomment-154524869.

## 

Derrick

**Comment by ezra-g** [comment]
GTK, thanks!

**Comment by derrickreimer** [comment]
This should all be working now (we are no longer DDoSing ourselves...). Sorry for the inconvenience!
