### ISSUE TITLE
Change stage when pull request summitted

### ISSUE THREAD

**Issue by carlshimer** [codetree/feedback#161]
I want any tickets tied to a branch to be put in the "ready for review" stage when a pull request is submitted.  When the PR is merged I want the ticket to move to "ready to release" stage so I know what features are going out.

Right now all of these steps are manual. Some automation would be nice.

**Comment by derrickreimer** [comment]
Absolutely agree! This is in the dev queue - no ETA just yet, but I will keep you posted.

**Comment by chadbay** [comment]
The more automation the better, I would use this too.

**Comment by sfitts** [comment]
This issue is ancient, so it may well be dead (and one half of it has been implemented).  However, we'd like to see the second half happen too -- that is the option to move an issue to a given stage (such as "ready to release") when its associated PR is merged into the default branch.  Currently the only options are to either close or do nothing.

**Comment by ac21** [comment]
@sfitts - part 1) move on create PR is automation that already exists;  part 2) is covered in #314;  I'm closing this but `+1` your interest in 314.
