### ISSUE TITLE
Changing order in list view doesn't take effect

### ISSUE THREAD

**Issue by ezra-g** [codetree/feedback#169]
The drag&drop interaction appears to work but a moment later the issues snap back to their original order in the table. We're seeing 503s in the console as in https://github.com/codetree/feedback/issues/139 - Not sure if those are related. Sorting in priority order is fairly important to our sprint planning process so we'd love if at all possible to see this one resolved in the semi nearish approximate future-ish timeframe :). Thanks!

**Comment by derrickreimer** [comment]
Hmm this should not be happening - are you still observing bugginess on the list view?

**Comment by pushred** [comment]
I am and ordering is kinda the whole point for using Codetree for us.. I also managed to somehow end up with a clone when repeatedly reordering to demonstrate this.

![http://g.recordit.co/2DO0D7cGnQ.gif](http://g.recordit.co/2DO0D7cGnQ.gif)

I'm on Chrome 48.0.2564.97 (mac)

**Comment by pushred** [comment]
Looks like I ran into the scenario described in #38 but this was really unintuitive (at least coming from Trello) because my intention is to order issues in the same action as moving them from the backlog. Where they get dropped is their order, initially at least. I get the intention behind this but it just feels like a bug, like a failed sync action.
