### ISSUE TITLE
Name change is not being synced

### ISSUE THREAD

**Issue by premist** [codetree/feedback#173]
I changed issue name via GitHub's web interface, and Codetree doesn't update issue name accordingly. I tried 'Sync My GitHub Data' but it didn't help.

**Comment by premist** [comment]
I tried switching to the task board view and moving cards to different list, and it retrieved changed issue title.

**Comment by derrickreimer** [comment]
Hey @premist, unfortunately there are a few events that GitHub does not send out via webhooks - the two most painful being title/body changes and applying a milestone. We poll the API hourly to pull in those changes. We are about ready to ship a brand new issue editor in Codetree, so that it will be much easier to make those changes on the Codetree side.
