### ISSUE TITLE
Potential race condition during issue creation

### ISSUE THREAD

**Issue by dphaener** [codetree/feedback#19]
Creating an issue returned an error, and it looks like the error div isn't there for the particular error, so the JS pooped out.

![screen shot 2014-12-28 at 9 54 51 pm](https://cloud.githubusercontent.com/assets/5187971/5566433/86ea44c6-8edc-11e4-8a23-af7fd02429a3.png)

**Comment by derrickreimer** [comment]
Dropping this here for my own reference: https://www.honeybadger.io/projects/39461/faults/10274360#notice-summary

Appears to be caused by race condition that has only happened once -- I think you have bad luck my friend :). It appears that the issue did get created on GitHub, judging by the stack trace. Can you confirm?

**Comment by dphaener** [comment]
hahaha, just my luck. Yeah it was created just fine, popped up after a few minutes.
