### ISSUE TITLE
Show repo name on Milestones as well

### ISSUE THREAD

**Issue by onedanshow** [codetree/feedback#207]
I love the Milestones view.  However, it would be nice if they include the repo that they're each from.  I'd like to use this view as the high-level view of what all is being worked on.  The work around is to put a prefix in front of all the milestone names.

This is essentially another checkbox after "Show repository name in issue list" for "Show repository name in milestone list"

**Comment by kareem** [comment]
Hi @onedanshow Milestones in Codetree are created in every repo for a project.  Let's say you have a project called Foobar that shows issues from two repos called (wait for it) Foo and Bar.  In Codetree you create a milestone called Baz.  Codetree will create the Baz milestone in both the Foo and Bar projects in GitHub. 

So I don't think showing repo name in the milestone view makes sense, because every milestone would belong to every repo.

Does that make sense, or am I missing something?

**Comment by marcospereira** [comment]
Hi @kareem,

There is the opposite flow where milestones were created in Github and, when using Codetree, you can't tell which project owns that milestone. For example, consider that Foo and Bar have the following milestones **before integrating with Codetree**:

1. Foo: 1.2.3, 1.2.4, 1.2.5
2. Bar: 1.2.5, 1.2.6, 2.0.0

It is confusing to know which project owns "1.2.3" (only "1.2.5" is in both projects) and I have to remember it myself. More repositories you add, more confuse it gets. Here is a real example:

![screen shot 2017-08-23 at 2 27 42 pm](https://user-images.githubusercontent.com/4576/29629457-5318cce2-880f-11e7-9e49-bf7f9ad801ba.png)

**Comment by kareemlmc** [comment]
@marcospereira good point.  Can you help me understand why it's important to know which GitHub repo owns a milestone?  Once you have an issue in a _different_ repo in the same project as the repo that owns the milestone, Codetree will create milestone in the new repo.  So at that point the milestone will live in both repos.

**Comment by kareem** [comment]
Hi @marcospereira can you help me understand why it's important to know which repo owns a milestone?

Once you have an issue in a _different_ repo in the same milestone, Codetree will create the milestone in that new repo.  At that point the milestone will live in both repos.
