### ISSUE TITLE
Clicking on a milestones always switches everything to the list view

### ISSUE THREAD

**Issue by p8** [codetree/feedback#217]
I have the task board view set as default.
Whenever I click on a Milestone I always get the list view. After that all my saved shortcuts use the list view as well.
I would expect to see the taskboard view for all views unless I change it myself. Not when I click on a Milestone.

**Comment by kareem** [comment]
Agreed. We're working on fixing this. Sit tight. Thanks Petrik.

**Comment by p8** [comment]
Great!

**Comment by kareem** [comment]
Hi @p8, we've dug into this a bit more.  When you click any of the custom stage shortcuts that Codetree creates automatically, you should be automatically taken to List View.  This is because you're viewing all the tickets in a single stage, which doesn't make sense to see in Board view (it would be one column).  Subsequent clicks on shortcut links will keep you in list view because when you create a shortcut Codetree doesn't keep track of whether you're in Board or List view (we have a ticket to address this).  

You may think that the Default View setting would flip you back into board view, but right now all Default View does is show you List or Board view as a default when you log into Codetree.

However, you **shouldn't** be seeing List View when you click on a Milestone shortcut that you've created OR a Milestone on an issue card from board view.  Both shortcuts and milestones on issue cards respect the view you're currently in.  If you're seeing this behavior it's a bug and I'd love to understand how that's happening (could you record a vid or animated gif?)

I think the repro steps would be:
1. Go to board view
2. Click on milestone on card <== you should stay in board view

OR
1. Go to board view
2. Click on shortcut to milestone <== you should stay in board view

If you're in List view in either of the above two situations please let me know!

**Comment by p8** [comment]
Hi Kareem,
This will probably be fixed when Codetree keeps track of whether you're in Board or List view.
What I'm doing is the following:
1. I click on the test shortcut and see the taskboard
2. I click on the milestones and see 1 milestone called test
3. I click on the milestone test and see a list view instead of the taskboard (this sets the view to list).
4. I click on the test shortcut and I see the list view but I'd expect to see the taskboard view.

![out](https://cloud.githubusercontent.com/assets/28561/19838144/5920ae00-9ec9-11e6-9419-faad925a9dd3.gif)

**Comment by kareem** [comment]
Thanks @p8 that's super helpful.  You're right, this should be addressed when we deal with the the board view / list view issue.

**Comment by ac21** [comment]
@p8 - milestones and other links now utilize default preferences, so will stick to the task board is desired.  implemented over the summer.  closing
