### ISSUE TITLE
Make the first column (aka. untriaged) to consider the provided Milestone in the filter

### ISSUE THREAD

**Issue by haikalpribadi** [codetree/feedback#273]
At the moment, the first column ignores the milestone provided in the filter.

This makes it very confusing and misleading to use the board view of the filter. Take a simple example: we want to build a kanban board for a given milestone, say v1.5. So we make filter with to settings: view=board, and milestone=v1.5. However, when we go to the filter "Milestone v1.5 board", we see all the open/untriaged issues in the first column. This makes it very difficult for us to scope our work.

Is it possible for you to do a simple toggle in the project setting for "filter untriaged with Milestone"? Envisioning the code that goes into this, this should be fairly simple to implement and shouldn't break anyone's workflow.

**Comment by kareem** [comment]
Hey @haikalpribadi can you help me understand a little more why this is painful for you?  Is the issue that the column is there at all?  Because if so you can hide it by toggling it to hidden at the bottom of the page:

<img width="569" alt="unified - board 2018-09-23 14-36-47" src="https://user-images.githubusercontent.com/26123/45931030-25ed8200-bf3e-11e8-9cf2-bfe22cf81f6e.png">

**Comment by haikalpribadi** [comment]
Hi @kareem, 

We need the open/untriaged/first column in the board, to know what are the open issues in that milestone. Thus, if we hide the first column, it doesn't become a solution for us.
