### ISSUE TITLE
How can we delete a CodeTree organisation?

### ISSUE THREAD

**Issue by haikalpribadi** [codetree/feedback#281]
I want to delete a CodeTree organisation, but I can't find the the ability to do so?

**Comment by rstocker99** [comment]
Right now the only way to delete an org is to file a ticket with support. We've got adding the delete button on our list but it's not high priority right now.

**Comment by ac21** [comment]
closing: deleting a project is now enabled directly through your organization projects view.

**Comment by sergeyklay** [comment]
Why this issue was closed? Deleting _organization_ is not implemented, only organization's _projects_.  I tried to delete the organization 
<img width="563" alt="image" src="https://user-images.githubusercontent.com/1256298/70910633-c4b93f00-2018-11ea-9f3a-f68aa209dc6e.png">
and got this
<img width="621" alt="image" src="https://user-images.githubusercontent.com/1256298/70910562-a2272600-2018-11ea-8e43-bc622c326f3c.png">
