### ISSUE TITLE
Re-ordering issues isn't sticking

### ISSUE THREAD

**Issue by veganstraightedge** [codetree/feedback#38]
I have a [milestone](https://codetree.com/projects/b1SW/issues?milestone=Public+Feed) that has 27 issues in it. So, there are issues "above the fold" with a white background and some "below the fold" with background color of `#fdf9f6`.

When I drag an issue from the white section to the `#fdf9f6` section to re-order it, the issue snaps back to its original position.

**Comment by veganstraightedge** [comment]
The menu item `move to bottom` is also only moving the issue to the bottom of the white section.

**Comment by derrickreimer** [comment]
This is actually by design, although it probably warrants better explanation to the user to avoid confusion. Issues with a white background are "ordered", while those with a tan background are strictly "unordered". The two can't be intermixed, so dragging an issue below the block of ordered issues will cause it to move to the lowest possible ordered position.

The reason for this behavior is to allow things to be in an "unprioritized" state. E.g. if the PM has not yet decided the order of a batch of issues, you wouldn't want folks assuming there is an explicit ordering for them.

**Comment by veganstraightedge** [comment]
Ooooh. I got around it by dragging all of the unordered ones up to the ordered ones section. Then re-ordering to the way I want. 

Thanks for clarifying.

**Comment by pushred** [comment]
What about another workflow list, like Unprioritized or To Prioritize?
