### ISSUE TITLE
Switching milestone-based / assignee-based interface after a project is created?

### ISSUE THREAD

**Issue by rinopo** [codetree/feedback#44]
Is it possible to switch between milestone-based / assignee-based interface after a project has been created?

I'm talking about the "prioritization" setting that I've chosen when creating my project.

![new project codetree](https://cloud.githubusercontent.com/assets/45791/5871450/05b578cc-a321-11e4-8378-aff1d36b04d7.png)

**Comment by derrickreimer** [comment]
This is not available in the user settings yet, but I can update it manually if you'd like. This can actually be a pretty destructive action, since it wipes out all your manual ordering of issues. Shoot me an email in support if you'd like me to update. You can also create a second project attached to the same repos if you are just looking to try out a different prioritization method.

**Comment by rinopo** [comment]
Hi,
Thanks for the reply.

>  This can actually be a pretty destructive action, since it wipes out all your manual ordering of issues.

Since I've already ordered some 40+ issues assigned to me, and it would be painful to do that again, I'd choose to stay with the current setting.

>  You can also create a second project attached to the same repos

Thanks for the suggestion.
This would be another pain for me though. My use case is that I have 50+ repos each having some issues assigned to me, and I hoped to manage those issues in one list with Codetree (and that seems to work :+1: ).
But the problem is that adding 50+ repos one by one from the current interface of Codetree isn't really convenient and prone to unintentional omission. This may be related to #5 .
