### ISSUE TITLE
Other users with 'Full Access' permission can't link additional repositories

### ISSUE THREAD

**Issue by beaugunderson** [codetree/feedback#70]
The select box at the bottom of the page doesn't exist when she accesses the 'edit' page for our project (with shortlink uFsu).

**Comment by derrickreimer** [comment]
@beaugunderson sorry for the delay. We are airing on the side of caution here by only allowing the owner to add repos, since we rely on the owner's credentials to install the webhook and that user needs admin-level permissions on GitHub side. I suppose we could still allow others to link repos as long as the owner also has admin access to them without too much re-architecture -- I'll take a closer look and keep in informed.

**Comment by beaugunderson** [comment]
cool, that makes sense--I think we can live with that (linking new repos doesn't happen very often) but would be good to describe that limitation on that page to avoid confusion. :)

cc @madprime
