### ISSUE TITLE
Pull requests detached from issues, behaving like unique cards

### ISSUE THREAD

**Issue by andrewborstein** [codetree/feedback#94]
While viewing `Issues` in the `Task Board` view, sometimes a PR will appear in two places (cards): 
1. attached to its associated issue 
2. floating on its own, as if it's an issue
## PR #2917

![screen shot 2015-07-14 at 1 40 36 pm](https://cloud.githubusercontent.com/assets/7654254/8680312/9c27a1ec-2a2e-11e5-948b-e185efe51d3a.png)
## PR #2928

![screen shot 2015-07-14 at 1 41 58 pm](https://cloud.githubusercontent.com/assets/7654254/8680313/9c2f9bae-2a2e-11e5-9339-e1501500c42c.png)

I haven't been able to verify it yet, but it seems like this may be resolved after the associated PR is merged or marked as deployed.

**Comment by derrickreimer** [comment]
Hi @andrewborstein! This will happen when both the pull request and the original issue is marked with a stage label (in this case "ready for qa"). We show PRs in the intermediate stages because some folks prefer to move their pull requests through stages, while others just move the original issue through the stages (and leave the PR without stage labels). 

In your case, it looks like it might be appropriate to just mark PRs with "ready for qa" and leave that stage label off the original issue. Would that work for you?

**Comment by andrewborstein** [comment]
Oh, interesting. Ok, that makes sense. I guess I thought the views on the lefthand side might change the way things are **grouped**, not just what's visible. 

For example, it would be _awesome_ to have the option to _always_ group things together in one of a few ways:
- a) Issue card with PRs attached below
- b) PR card with issues attached below

It seems like only **a** is possible right now, which gives the `Issues` view a lot more functionality than the `Pull Requests` view. Or it might be useful to be able to choose this grouping preference on a per-column/label basis. 

If the above isn't possible, we will probably just move PRs around at that stage, and just look for issue references within them (instead of codetree).

**Comment by kareem** [comment]
Seems sensible @andrewborstein.

**Comment by ac21** [comment]
closing for now - as some use cases desire to see the PR as a card and others want to see attached.
