### ISSUE TITLE
given milestone to ticket, doesn't show up under proper milestone

### ISSUE THREAD

**Issue by Dieterbe** [codetree/feedback#98]
our grafana repo has milestones like 0.17 and 0.16
those tickets show up fine in the right place.
however the board also shows tickets from another repo called customer-experience.
so i opened an existing ticket of the custom-experience repo and gave it milestone 0.17

it didn't show up in codetree list view under the proper milestone, but it does show up on the board.
this is after explicitly syncing a few times and waiting for about 5 minutes. going back to list view and it doesn't show again.

edit: in fact, in the board view, it also shows up if i select milestone 0.18 wtf

**Comment by derrickreimer** [comment]
Hey @Dieterbe, did you apply the milestone on the GitHub side? Unfortunately, GitHub does not send us a webhook when a milestone is applied to an issue or an issue title is updated. We have to fallback to periodically polling GitHub to propagate these changes back to Codetree.

At current time, the "Sync My GitHub Data" refreshes your permissions, owned repositories, etc. but does not perform full refreshes on projects, due to their intensive nature (in compute and API rate limits).

Projects are refreshed hourly - are these issues now properly categorized in your project?

FYI - to help alleviate this pain, we are doing two things:
- Lobbying GitHub to send us these webhooks
- Building a full issue editing interface in Codetree so it is dead easy to make most issue modifications on the Codetree side

**Comment by Dieterbe** [comment]
yes, github side.  now it works properly indeed, in both list and taskboard view.
i wasn't aware you could change milestone in codetree. so what are the changes we should make in codetree as opposed to GH if we want the changes to sync immediately? just milestones or also assignee, tags, ... ?
i'm quite interested in the issue editing interface in codetree because that workflow seems a bit clunky right now (zenhub does this quite nicely for example)
thanks!

**Comment by derrickreimer** [comment]
Just milestones - assignee and label updates propagate back to Codetree via webhooks almost instantly. Milestones can be applied in Codetree in the list view by clicking the milestone name on any given issue. I'll be sure to push out a big announcement when the full editing interface is available!
